name: heroku
on:
  push:
  schedule:
    - cron: '*/20 * * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: heroku-market
        run: ping springmvc-market.herokuapp.com && curl https://springmvc-market.herokuapp.com > /dev/null
