# This is a basic workflow to help you get started with Actions

name: crontab mail
on:
  push:
  schedule:
    - cron: '0 4 * * *'
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get weather
        run: bash ./main.sh
        
      - name: get date
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
        
      - name: Send mailer
        uses: dawidd6/action-send-mail@master
        with:
          server_addr: stmp.ym.163.com
          server_port: 994
          account: ${{secrets.MAIL_USER}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: no-reply
          from: no-reply@beet.tk - github action
          to: 1435978213@qq.com
          subject: Weather Today (${{env.REPORT_DATE}})
          body: file://main.html
          contentType: text/html
